### ISSUE TITLE
Spec 100%

### ISSUE THREAD

**Issue by shmielminz** [shmielminz/BeatTheStorm#1]

**Comment by leahlebovits** [comment]
-- LL Wow!! Really interesting and creative sounding game! Spec is detailed, clear and game sounds possible to implement. Looking forward to playing it!

**Comment by leahlebovits** [comment]
-- LL see general comments in hw repository issue. Once those comments are implemented, I will mark the spec 100%

**Comment by leahlebovits** [comment]
-- LL 100% Amazing Job!
