### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by shmielminz** [shmielminz/BeatTheStorm#3]

**Comment by shmielminz** [comment]
I know the code is messy, but first review the work.

**Comment by AshiraFriedman** [comment]
I will open a pull request and review the code now, since QA is basically done

**Comment by AshiraFriedman** [comment]
I starting reviewing the code but see a lot of commented out code.
Would you please be able to clean up the code, and only leave in what you intended as of now?
Let me know once that's done and I can start the review

**Comment by shmielminz** [comment]
Done

**Comment by AshiraFriedman** [comment]
I started the code review and wanted to push my changes but the push is failing.
Can you check if I have push permissions to this repo?

**Comment by shmielminz** [comment]
I don't know why it shouldn't work. But did you try to push to your forked repo? Or to mine? Maybe when you forked a repo you can't push directly to main repo only by creating a PR.

**Comment by AshiraFriedman** [comment]
I looked into it, it seems like by default the repo will be blocked from me pushing anything to it, as I'm not an admin to the repo.  Any changes I want to merge in have to be approved by you in a pull request.  However, when I had wanted to open a pull request, it wasn't working because I had no changed files.  I guess I can just open a pull request now and you can accept my changes and merge into your branch.  I feel like it's not the most efficient way of doing things, but if I have no other way to push to your branch, we can just do it like this.

**Comment by shmielminz** [comment]
I tried pushing with my CPU GitHub account, and I see I can't, but with PR it works ok. Just push the changes to your forked repo, and create a PR. (First sync the changes from my repo)

**Comment by shmielminz** [comment]
I think you can push already. I managed to push from my CPU GitHub account.

**Comment by AshiraFriedman** [comment]
Thank you, this was better than opening a pull request.
I'm just curious, what did you to allow me to push?  I want to know in order to be able to instruct other students...

**Comment by shmielminz** [comment]
Settings > Code and automation > Branches > Branch protection rules > Edit:
- Protect matching branches: Uncheck Require a pull request before merging. 
- Rules applied to everyone including administrators: Check Allow force pushes > Everyone. (Maybe can do Specify who can force push, and specify the name).

**Comment by shmielminz** [comment]
Fixed or replied on the comments

**Comment by AshiraFriedman** [comment]
Great job! Looks like it's good to go.  Please see my comments and then you can delete all commented code and submit the final version, and then I will do the final round of QA, just to make sure everything is good.

**Comment by shmielminz** [comment]
Done. I still plan to add some features. But this will have to wait for object oriented programming.

**Comment by AshiraFriedman** [comment]
Very nice work! Everything seems to be working well, the UI looks good and the code is very nice.
Well done
