### ISSUE TITLE
Bug found in "play against computer mode"

### ISSUE THREAD

**Issue by AshiraFriedman** [shmielminz/BeatTheStorm#4]
When playing in mode against computer, with "card only", player 1 can click on the card for player 2.  The player 2 box should not be clickable when playing against the computer

**Comment by shmielminz** [comment]
Not a bug really. You are changing your card/dice. Reason is because I created one event handler for both dice and card boxes. I can make it as 2 event handlers, or making the enabled property for player 2 box when in computer mode false.

**Comment by AshiraFriedman** [comment]
yes, I would do one of those 2 options

**Comment by AshiraFriedman** [comment]
Nice job
