### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by AshiraFriedman** [shmielminz/BeatTheStorm#6]
It's hard to see which way the the pieces move left to right etc, mayb eit would be a good idea to add arrows in the boxes at the end of the row pointing to where the player will continue.  Otherwise, it's hard to see if the pieces are just moving left to right, or if they are going left to right, then up, and then right to left.

**Comment by shmielminz** [comment]
Added some arrows. Didn't find the right ones, but it's ok

**Comment by AshiraFriedman** [comment]
These arrows are totally fine, however even the ones going up the 50 shaarei kedusha are pointing downwards, can you flip the arrow image to be pointing up?

**Comment by shmielminz** [comment]
No I tried to find a double sided arrow. When I find one I'll change it. Or I'll make a image.

**Comment by AshiraFriedman** [comment]
great
