### ISSUE TITLE
UI for MAUI app

### ISSUE THREAD

**Issue by shmielminz** [shmielminz/BeatTheStorm#9]

**Comment by AshiraFriedman** [comment]
Very nice work!
In the game tab, even when I open it in full screen, only around half of the game board is displayed and you have to scroll down to see the rest.  Please fix this (it's a better game experience to see the whole board to see what's happening easily)

**Comment by shmielminz** [comment]
I fixed it a bit. My plan is to make it a page not part of the nav. So the navbar on the game page will be replaced by the undo/redo and status. So the view will be better then.

When you remove the buttons you don't need to scroll on the game.

**Comment by AshiraFriedman** [comment]
Nice work! Okay that sounds good.
